  
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    ports:
      - ${LOCAL_PORT}:5432
    volumes:
      - ${LOCAL_PATH}:/var/lib/postgresql/data
